apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rhug-ottawa-devai
  description: RHUG prep repository.
  annotations:
    backstage.io/source-location: url:https://github.com/pittar-rhdh/rhug-ottawa-devai
    backstage.io/techdocs-ref: dir:.
    #argocd/app-name: rhug-ottawa-devai
  tags:
    - java
    - quarkus
  links:
    - url: https://github.com/pittar-rhdh/rhug-ottawa-devai
      title: Open in Dev Spaces
      icon: web
    - url: https://www.redhat.com/en/blog/channel/hybrid-cloud-infrastructure
      title: Red Hat Blog
      icon: web
spec:
  type: service
  lifecycle: production
  owner: group:default/teamlead
