apiVersion: v1
kind: Secret
metadata:
  annotations:
    controller.devfile.io/mount-as: env
  labels:
    app.kubernetes.io/component: workspaces-config
    app.kubernetes.io/part-of: che.eclipse.org
  name: claude-api-key
  namespace: openshift-devspaces
type: Opaque
stringData:
  ANTHROPIC_API_KEY: NotMyAPIKey
